### ISSUE TITLE
Look Like...

### ISSUE THREAD

**Issue by CyberSys** [nora-soderlund/SanAndreas#1]
Hm.. Look like another some one  projects
https://github.com/GTA-ASM/SanAndreasUnity
https://www.youtube.com/watch?v=hnInLUbobI8

https://github.com/mukaschultze/grand-theft-auto-for-unity

and some project maybe can use in future
https://github.com/GTA-ASM/SanAndreasUnity/issues/118

**Comment by nora-soderlund** [comment]
Not the same.
